package com.leasing.popular.wf.table.parametros.parametro;

// Generated 12/12/2009 10:26:43 AM by Hibernate Tools 3.2.4.GA

 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MpaParametro generated by hbm2java
 */
@Entity
@Table(name = "MPA_PARAMETRO")
public class MpaParametro implements java.io.Serializable {

	/**
	 * @uml.property  name="parCodigo"
	 */
	private Long parCodigo;
	/**
	 * @uml.property  name="parNombre"
	 */
	private String parNombre; 

	public MpaParametro() {
	}

	public MpaParametro(Long parCodigo) {
		this.parCodigo = parCodigo;
	}

	public MpaParametro(Long parCodigo, String parNombre) {
		this.parCodigo = parCodigo;
		this.parNombre = parNombre;
	}

	/**
	 * @return
	 * @uml.property  name="parCodigo"
	 */
	@Id
	 @Column(name = "PAR_CODIGO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getParCodigo() {
		return this.parCodigo;
	}

	/**
	 * @param  parCodigo
	 * @uml.property  name="parCodigo"
	 */
	public void setParCodigo(Long parCodigo) {
		this.parCodigo = parCodigo;
	}

	/**
	 * @return
	 * @uml.property  name="parNombre"
	 */
	@Column(name = "PAR_NOMBRE", length = 100)
	public String getParNombre() {
		return this.parNombre;
	}

	/**
	 * @param  parNombre
	 * @uml.property  name="parNombre"
	 */
	public void setParNombre(String parNombre) {
		this.parNombre = parNombre.toUpperCase();
	}

 

}
