package com.leasing.popular.wf.table.negocio.negocio;

// Generated 31/01/2010 09:41:02 AM by Hibernate Tools 3.2.4.GA

 
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.leasing.popular.wf.table.negocio.persona.McomPersonas;
import com.leasing.popular.wf.table.parametros.valores.MpaValores;

/**
 * McomNegocio generated by hbm2java
 */
@Entity
@Table(name = "MCOM_NEGOCIO")
public class McomNegocio implements java.io.Serializable {

	private BigDecimal negId;
	private MpaValores mpaValoresByFkNegocioValoresCausaldesi1;
	private MpaValores mpaValoresByFkNegocioValoresContacomer;
	private MpaValores mpaValoresByFkNegocioValoresLinea;
	private MpaValores mpaValoresByFkNegocioValoresTipo;
	private MpaValores mpaValoresByFkNegocioValoresTipobien;
	private MpaValores mpaValoresByFkNegocioValoresFuenegocio;
	private MpaValores mpaValoresByFkNegocioValoresTiponegocio;
	private MpaValores mpaValoresByFkNegocioValoresClase;
	private MpaValores mpaValoresByFkNegocioValoresMarca;
	private MpaValores mpaValoresByFkNegocioValoresEstado;
	private MpaValores mpaValoresByFkNegocioValoresEjecutivo;
	private MpaValores mpaValoresByFkNegocioValoresRadicador;
	private McomPersonas mcomPersonasByFkClientePersonas;
	private MpaValores mpaValoresByFkNegocioValoresPlan;
	private MpaValores mpaValoresByFkNegocioValoresCuasaldesi2;
	private McomPersonas mcomPersonasByFkProveedorPersonas;
	private MpaValores mpaValoresByFkNegocioValoresCausaldesi3;
	private BigDecimal negCont;
	private Date negFecha;
	private BigDecimal negValorTotal;
	private BigDecimal negMontoSolicitado;
	private Date negFechaDatacredito;
	private Date negFechaDocumentos1;
	private Date negFechaRecepcion1;
	private Date negFechaRiesgo;
	private String negObservaciones;
 



	public McomNegocio() {
	}

	public McomNegocio(BigDecimal negId,
			McomPersonas mcomPersonasByFkClientePersonas, Date negFecha) {
		this.negId = negId;
		this.mcomPersonasByFkClientePersonas = mcomPersonasByFkClientePersonas;
		this.negFecha = negFecha;
	}

	public McomNegocio(BigDecimal negId,
			MpaValores mpaValoresByFkNegocioValoresCausaldesi1,
			MpaValores mpaValoresByFkNegocioValoresContacomer,
			MpaValores mpaValoresByFkNegocioValoresLinea,
			MpaValores mpaValoresByFkNegocioValoresTipo,
			MpaValores mpaValoresByFkNegocioValoresTipobien,
			MpaValores mpaValoresByFkNegocioValoresFuenegocio,
			MpaValores mpaValoresByFkNegocioValoresTiponegocio,
			MpaValores mpaValoresByFkNegocioValoresClase,
			MpaValores mpaValoresByFkNegocioValoresMarca,
			MpaValores mpaValoresByFkNegocioValoresEstado,
			MpaValores mpaValoresByFkNegocioValoresEjecutivo,
			MpaValores mpaValoresByFkNegocioValoresRadicador,
			McomPersonas mcomPersonasByFkClientePersonas,
			MpaValores mpaValoresByFkNegocioValoresPlan,
			MpaValores mpaValoresByFkNegocioValoresCuasaldesi2,
			McomPersonas mcomPersonasByFkProveedorPersonas,
			MpaValores mpaValoresByFkNegocioValoresCausaldesi3,
			BigDecimal negCont, Date negFecha, BigDecimal negValorTotal,
			BigDecimal negMontoSolicitado, Date negFechaDatacredito,
			Date negFechaDocumentos1, Date negFechaRecepcion1,
			Date negFechaRiesgo, String negObservaciones) {
		this.negId = negId;
		this.mpaValoresByFkNegocioValoresCausaldesi1 = mpaValoresByFkNegocioValoresCausaldesi1;
		this.mpaValoresByFkNegocioValoresContacomer = mpaValoresByFkNegocioValoresContacomer;
		this.mpaValoresByFkNegocioValoresLinea = mpaValoresByFkNegocioValoresLinea;
		this.mpaValoresByFkNegocioValoresTipo = mpaValoresByFkNegocioValoresTipo;
		this.mpaValoresByFkNegocioValoresTipobien = mpaValoresByFkNegocioValoresTipobien;
		this.mpaValoresByFkNegocioValoresFuenegocio = mpaValoresByFkNegocioValoresFuenegocio;
		this.mpaValoresByFkNegocioValoresTiponegocio = mpaValoresByFkNegocioValoresTiponegocio;
		this.mpaValoresByFkNegocioValoresClase = mpaValoresByFkNegocioValoresClase;
		this.mpaValoresByFkNegocioValoresMarca = mpaValoresByFkNegocioValoresMarca;
		this.mpaValoresByFkNegocioValoresEstado = mpaValoresByFkNegocioValoresEstado;
		this.mpaValoresByFkNegocioValoresEjecutivo = mpaValoresByFkNegocioValoresEjecutivo;
		this.mpaValoresByFkNegocioValoresRadicador = mpaValoresByFkNegocioValoresRadicador;
		this.mcomPersonasByFkClientePersonas = mcomPersonasByFkClientePersonas;
		this.mpaValoresByFkNegocioValoresPlan = mpaValoresByFkNegocioValoresPlan;
		this.mpaValoresByFkNegocioValoresCuasaldesi2 = mpaValoresByFkNegocioValoresCuasaldesi2;
		this.mcomPersonasByFkProveedorPersonas = mcomPersonasByFkProveedorPersonas;
		this.mpaValoresByFkNegocioValoresCausaldesi3 = mpaValoresByFkNegocioValoresCausaldesi3;
		this.negCont = negCont;
		this.negFecha = negFecha;
		this.negValorTotal = negValorTotal;
		this.negMontoSolicitado = negMontoSolicitado;
		this.negFechaDatacredito = negFechaDatacredito;
		this.negFechaDocumentos1 = negFechaDocumentos1;
		this.negFechaRecepcion1 = negFechaRecepcion1;
		this.negFechaRiesgo = negFechaRiesgo;
		this.negObservaciones = negObservaciones;
	}

	/**
	 * @return
	 * @uml.property  name="negId"
	 */
	@Id
	@Column(name = "NEG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNegId() {
		return this.negId;
	}

	/**
	 * @param  negId
	 * @uml.property  name="negId"
	 */
	public void setNegId(BigDecimal negId) {
		this.negId = negId;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresCausaldesi1"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_CAUSAL_DESI1", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_CAUSALDESI1", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresCausaldesi1() {
		return this.mpaValoresByFkNegocioValoresCausaldesi1;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresCausaldesi1
	 * @uml.property  name="mpaValoresByFkNegocioValoresCausaldesi1"
	 */
	public void setMpaValoresByFkNegocioValoresCausaldesi1(
			MpaValores mpaValoresByFkNegocioValoresCausaldesi1) {
		this.mpaValoresByFkNegocioValoresCausaldesi1 = mpaValoresByFkNegocioValoresCausaldesi1;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresContacomer"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_CONTA_COMERCIAL", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_CONTCOMERCIAL", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresContacomer() {
		return this.mpaValoresByFkNegocioValoresContacomer;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresContacomer
	 * @uml.property  name="mpaValoresByFkNegocioValoresContacomer"
	 */
	public void setMpaValoresByFkNegocioValoresContacomer(
			MpaValores mpaValoresByFkNegocioValoresContacomer) {
		this.mpaValoresByFkNegocioValoresContacomer = mpaValoresByFkNegocioValoresContacomer;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresLinea"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_LINEA", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_LINEA", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresLinea() {
		return this.mpaValoresByFkNegocioValoresLinea;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresLinea
	 * @uml.property  name="mpaValoresByFkNegocioValoresLinea"
	 */
	public void setMpaValoresByFkNegocioValoresLinea(
			MpaValores mpaValoresByFkNegocioValoresLinea) {
		this.mpaValoresByFkNegocioValoresLinea = mpaValoresByFkNegocioValoresLinea;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresTipo"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_TIPO", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_TIPO", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresTipo() {
		return this.mpaValoresByFkNegocioValoresTipo;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresTipo
	 * @uml.property  name="mpaValoresByFkNegocioValoresTipo"
	 */
	public void setMpaValoresByFkNegocioValoresTipo(
			MpaValores mpaValoresByFkNegocioValoresTipo) {
		this.mpaValoresByFkNegocioValoresTipo = mpaValoresByFkNegocioValoresTipo;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresTipobien"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_TIPO_BIEN", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_TIPOBIEN", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresTipobien() {
		return this.mpaValoresByFkNegocioValoresTipobien;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresTipobien
	 * @uml.property  name="mpaValoresByFkNegocioValoresTipobien"
	 */
	public void setMpaValoresByFkNegocioValoresTipobien(
			MpaValores mpaValoresByFkNegocioValoresTipobien) {
		this.mpaValoresByFkNegocioValoresTipobien = mpaValoresByFkNegocioValoresTipobien;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresFuenegocio"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_FUENTE_NEGOCIO", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_FUENEGOCIO", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresFuenegocio() {
		return this.mpaValoresByFkNegocioValoresFuenegocio;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresFuenegocio
	 * @uml.property  name="mpaValoresByFkNegocioValoresFuenegocio"
	 */
	public void setMpaValoresByFkNegocioValoresFuenegocio(
			MpaValores mpaValoresByFkNegocioValoresFuenegocio) {
		this.mpaValoresByFkNegocioValoresFuenegocio = mpaValoresByFkNegocioValoresFuenegocio;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresTiponegocio"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_TIPO_NEGOCIO", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_TIPONEGOCIO", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresTiponegocio() {
		return this.mpaValoresByFkNegocioValoresTiponegocio;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresTiponegocio
	 * @uml.property  name="mpaValoresByFkNegocioValoresTiponegocio"
	 */
	public void setMpaValoresByFkNegocioValoresTiponegocio(
			MpaValores mpaValoresByFkNegocioValoresTiponegocio) {
		this.mpaValoresByFkNegocioValoresTiponegocio = mpaValoresByFkNegocioValoresTiponegocio;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresClase"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_CLASE", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_CLASE", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresClase() {
		return this.mpaValoresByFkNegocioValoresClase;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresClase
	 * @uml.property  name="mpaValoresByFkNegocioValoresClase"
	 */
	public void setMpaValoresByFkNegocioValoresClase(
			MpaValores mpaValoresByFkNegocioValoresClase) {
		this.mpaValoresByFkNegocioValoresClase = mpaValoresByFkNegocioValoresClase;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresMarca"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_MARCA", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_MARCA", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresMarca() {
		return this.mpaValoresByFkNegocioValoresMarca;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresMarca
	 * @uml.property  name="mpaValoresByFkNegocioValoresMarca"
	 */
	public void setMpaValoresByFkNegocioValoresMarca(
			MpaValores mpaValoresByFkNegocioValoresMarca) {
		this.mpaValoresByFkNegocioValoresMarca = mpaValoresByFkNegocioValoresMarca;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresEstado"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_ESTADO", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_ESTADO", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresEstado() {
		return this.mpaValoresByFkNegocioValoresEstado;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresEstado
	 * @uml.property  name="mpaValoresByFkNegocioValoresEstado"
	 */
	public void setMpaValoresByFkNegocioValoresEstado(
			MpaValores mpaValoresByFkNegocioValoresEstado) {
		this.mpaValoresByFkNegocioValoresEstado = mpaValoresByFkNegocioValoresEstado;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresEjecutivo"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_EJECUTIVO", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_EJECUTIVO", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresEjecutivo() {
		return this.mpaValoresByFkNegocioValoresEjecutivo;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresEjecutivo
	 * @uml.property  name="mpaValoresByFkNegocioValoresEjecutivo"
	 */
	public void setMpaValoresByFkNegocioValoresEjecutivo(
			MpaValores mpaValoresByFkNegocioValoresEjecutivo) {
		this.mpaValoresByFkNegocioValoresEjecutivo = mpaValoresByFkNegocioValoresEjecutivo;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresRadicador"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_RADICADOR", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_RADICADOR", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresRadicador() {
		return this.mpaValoresByFkNegocioValoresRadicador;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresRadicador
	 * @uml.property  name="mpaValoresByFkNegocioValoresRadicador"
	 */
	public void setMpaValoresByFkNegocioValoresRadicador(
			MpaValores mpaValoresByFkNegocioValoresRadicador) {
		this.mpaValoresByFkNegocioValoresRadicador = mpaValoresByFkNegocioValoresRadicador;
	}

	/**
	 * @return
	 * @uml.property  name="mcomPersonasByFkClientePersonas"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_ID_CLIENTE", referencedColumnName = "PER_IDENTIFICACION", nullable = false),
			@JoinColumn(name = "NEG_TIPO_ID_CLIENTE", referencedColumnName = "PER_TIPO_IDENTIFICACION", nullable = false),
			@JoinColumn(name = "NEG_PARA_TIPO_ID_CLIENTE", referencedColumnName = "PER_PARA_TIPO_ID", nullable = false) })
	public McomPersonas getMcomPersonasByFkClientePersonas() {
		return this.mcomPersonasByFkClientePersonas;
	}

	/**
	 * @param  mcomPersonasByFkClientePersonas
	 * @uml.property  name="mcomPersonasByFkClientePersonas"
	 */
	public void setMcomPersonasByFkClientePersonas(
			McomPersonas mcomPersonasByFkClientePersonas) {
		this.mcomPersonasByFkClientePersonas = mcomPersonasByFkClientePersonas;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresPlan"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_PLAN", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_PLAN", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresPlan() {
		return this.mpaValoresByFkNegocioValoresPlan;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresPlan
	 * @uml.property  name="mpaValoresByFkNegocioValoresPlan"
	 */
	public void setMpaValoresByFkNegocioValoresPlan(
			MpaValores mpaValoresByFkNegocioValoresPlan) {
		this.mpaValoresByFkNegocioValoresPlan = mpaValoresByFkNegocioValoresPlan;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresCuasaldesi2"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_CAUSAL_DESI2", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_CAUSALDESI2", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresCuasaldesi2() {
		return this.mpaValoresByFkNegocioValoresCuasaldesi2;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresCuasaldesi2
	 * @uml.property  name="mpaValoresByFkNegocioValoresCuasaldesi2"
	 */
	public void setMpaValoresByFkNegocioValoresCuasaldesi2(
			MpaValores mpaValoresByFkNegocioValoresCuasaldesi2) {
		this.mpaValoresByFkNegocioValoresCuasaldesi2 = mpaValoresByFkNegocioValoresCuasaldesi2;
	}

	/**
	 * @return
	 * @uml.property  name="mcomPersonasByFkProveedorPersonas"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_ID_PROVEEDOR", referencedColumnName = "PER_IDENTIFICACION"),
			@JoinColumn(name = "NEG_TIPO_ID_PROVEEDOR", referencedColumnName = "PER_TIPO_IDENTIFICACION"),
			@JoinColumn(name = "NEG_PARAM_ID_PROVEEDOR", referencedColumnName = "PER_PARA_TIPO_ID") })
	public McomPersonas getMcomPersonasByFkProveedorPersonas() {
		return this.mcomPersonasByFkProveedorPersonas;
	}

	/**
	 * @param  mcomPersonasByFkProveedorPersonas
	 * @uml.property  name="mcomPersonasByFkProveedorPersonas"
	 */
	public void setMcomPersonasByFkProveedorPersonas(
			McomPersonas mcomPersonasByFkProveedorPersonas) {
		this.mcomPersonasByFkProveedorPersonas = mcomPersonasByFkProveedorPersonas;
	}

	/**
	 * @return
	 * @uml.property  name="mpaValoresByFkNegocioValoresCausaldesi3"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "NEG_CAUSAL_DESI3", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "NEG_PARA_CAUSALDESI3", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkNegocioValoresCausaldesi3() {
		return this.mpaValoresByFkNegocioValoresCausaldesi3;
	}

	/**
	 * @param  mpaValoresByFkNegocioValoresCausaldesi3
	 * @uml.property  name="mpaValoresByFkNegocioValoresCausaldesi3"
	 */
	public void setMpaValoresByFkNegocioValoresCausaldesi3(
			MpaValores mpaValoresByFkNegocioValoresCausaldesi3) {
		this.mpaValoresByFkNegocioValoresCausaldesi3 = mpaValoresByFkNegocioValoresCausaldesi3;
	}

	/**
	 * @return
	 * @uml.property  name="negCont"
	 */
	@Column(name = "NEG_CONT", precision = 22, scale = 0)
	public BigDecimal getNegCont() {
		return this.negCont;
	}

	/**
	 * @param  negCont
	 * @uml.property  name="negCont"
	 */
	public void setNegCont(BigDecimal negCont) {
		this.negCont = negCont;
	}

	/**
	 * @return
	 * @uml.property  name="negFecha"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEG_FECHA", nullable = false, length = 7)
	public Date getNegFecha() {
		return this.negFecha;
	}

	/**
	 * @param  negFecha
	 * @uml.property  name="negFecha"
	 */
	public void setNegFecha(Date negFecha) {
		this.negFecha = negFecha;
	}

	/**
	 * @return
	 * @uml.property  name="negValorTotal"
	 */
	@Column(name = "NEG_VALOR_TOTAL", precision = 126, scale = 0)
	public BigDecimal getNegValorTotal() {
		return this.negValorTotal;
	}

	/**
	 * @param  negValorTotal
	 * @uml.property  name="negValorTotal"
	 */
	public void setNegValorTotal(BigDecimal negValorTotal) {
		this.negValorTotal = negValorTotal;
	}

	/**
	 * @return
	 * @uml.property  name="negMontoSolicitado"
	 */
	@Column(name = "NEG_MONTO_SOLICITADO", precision = 126, scale = 0)
	public BigDecimal getNegMontoSolicitado() {
		return this.negMontoSolicitado;
	}

	/**
	 * @param  negMontoSolicitado
	 * @uml.property  name="negMontoSolicitado"
	 */
	public void setNegMontoSolicitado(BigDecimal negMontoSolicitado) {
		this.negMontoSolicitado = negMontoSolicitado;
	}

	/**
	 * @return
	 * @uml.property  name="negFechaDatacredito"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEG_FECHA_DATACREDITO", length = 7)
	public Date getNegFechaDatacredito() {
		return this.negFechaDatacredito;
	}

	/**
	 * @param  negFechaDatacredito
	 * @uml.property  name="negFechaDatacredito"
	 */
	public void setNegFechaDatacredito(Date negFechaDatacredito) {
		this.negFechaDatacredito = negFechaDatacredito;
	}

	/**
	 * @return
	 * @uml.property  name="negFechaDocumentos1"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEG_FECHA_DOCUMENTOS1", length = 7)
	public Date getNegFechaDocumentos1() {
		return this.negFechaDocumentos1;
	}

	/**
	 * @param  negFechaDocumentos1
	 * @uml.property  name="negFechaDocumentos1"
	 */
	public void setNegFechaDocumentos1(Date negFechaDocumentos1) {
		this.negFechaDocumentos1 = negFechaDocumentos1;
	}

	/**
	 * @return
	 * @uml.property  name="negFechaRecepcion1"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEG_FECHA_RECEPCION1", length = 7)
	public Date getNegFechaRecepcion1() {
		return this.negFechaRecepcion1;
	}

	/**
	 * @param  negFechaRecepcion1
	 * @uml.property  name="negFechaRecepcion1"
	 */
	public void setNegFechaRecepcion1(Date negFechaRecepcion1) {
		this.negFechaRecepcion1 = negFechaRecepcion1;
	}

	/**
	 * @return
	 * @uml.property  name="negFechaRiesgo"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEG_FECHA_RIESGO", length = 7)
	public Date getNegFechaRiesgo() {
		return this.negFechaRiesgo;
	}

	/**
	 * @param  negFechaRiesgo
	 * @uml.property  name="negFechaRiesgo"
	 */
	public void setNegFechaRiesgo(Date negFechaRiesgo) {
		this.negFechaRiesgo = negFechaRiesgo;
	}

	/**
	 * @return
	 * @uml.property  name="negObservaciones"
	 */
	@Column(name = "NEG_OBSERVACIONES", length = 50)
	public String getNegObservaciones() {
		return this.negObservaciones;
	}

	/**
	 * @param  negObservaciones
	 * @uml.property  name="negObservaciones"
	 */
	public void setNegObservaciones(String negObservaciones) {
		this.negObservaciones = negObservaciones==null?negObservaciones:negObservaciones.toUpperCase();
	}
	


}
