package com.leasing.popular.wf.table.seguridad.roles;
 

//Generated 21/11/2009 03:55:19 PM by Hibernate Tools 3.2.5.Beta
 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jboss.seam.annotations.Name;

/**
 * MsegRoles generated by hbm2java
 */
@Entity
@Name("msegRoles")
@Table(name = "MSEG_ROLES")
public class MsegRoles implements java.io.Serializable {

	/**
	 * @uml.property  name="rolCodigo"
	 */
	private Long rolCodigo;
	/**
	 * @uml.property  name="rolNombreRol"
	 */
	private String rolNombreRol;  

	public MsegRoles() {
	}

	public MsegRoles(Long rolCodigo, String rolNombreRol) {
		this.rolCodigo = rolCodigo;
		this.rolNombreRol = rolNombreRol;
	}
 

	
	
	/**
	 * @return
	 * @uml.property  name="rolCodigo"
	 */
	@Id
	@Column(name = "ROL_CODIGO" )
	public Long getRolCodigo() {
		return this.rolCodigo;
	}

	/**
	 * @param  rolCodigo
	 * @uml.property  name="rolCodigo"
	 */
	public void setRolCodigo(Long rolCodigo) {
		this.rolCodigo = rolCodigo;
	}

	/**
	 * @return
	 * @uml.property  name="rolNombreRol"
	 */
	@Column(name = "ROL_NOMBRE_ROL", nullable = false, length = 30)
	public String getRolNombreRol() {
		return this.rolNombreRol;
	}

	/**
	 * @param  rolNombreRol
	 * @uml.property  name="rolNombreRol"
	 */
	public void setRolNombreRol(String rolNombreRol) {
		this.rolNombreRol = rolNombreRol.trim().toUpperCase();
	}

	
 
 

}
