package com.leasing.popular.wf.table.seguridad.roles;

// Generated 22/11/2009 11:45:06 AM by Hibernate Tools 3.2.5.Beta

 
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.jboss.seam.annotations.Name;

import com.leasing.popular.wf.table.seguridad.modulo.MsegModulos;
import com.leasing.popular.wf.table.seguridad.modulo.MsegRolmodulosId;

/**
 * MsegRolmodulos generated by hbm2java
 */
@Entity
@Name("msegRolmodulos")
@Table(name = "MSEG_ROLMODULOS")
public class MsegRolmodulos implements java.io.Serializable {

	/**
	 * @uml.property  name="id"
	 * @uml.associationEnd  
	 */
	private MsegRolmodulosId id;
	/**
	 * @uml.property  name="msegRoles"
	 * @uml.associationEnd  
	 */
	private MsegRoles msegRoles;
	/**
	 * @uml.property  name="msegModulos"
	 * @uml.associationEnd  
	 */
	private MsegModulos msegModulos;
	/**
	 * @uml.property  name="rolConsulta"
	 */
	private Long rolConsulta;
	/**
	 * @uml.property  name="rolEliminar"
	 */
	private Long rolEliminar;
	/**
	 * @uml.property  name="rolActualizar"
	 */
	private Long rolActualizar;
	/**
	 * @uml.property  name="rolInsertar"
	 */
	private Long rolInsertar;
 

	public MsegRolmodulos() {
	}

	public MsegRolmodulos(MsegRolmodulosId id, MsegRoles msegRoles,
			MsegModulos msegModulos) {
		this.id = id;
		
		this.msegRoles = msegRoles;
		this.msegModulos = msegModulos;
	}

	public MsegRolmodulos(MsegRolmodulosId id, MsegRoles msegRoles,
			MsegModulos msegModulos, Long rolConsulta,
			Long rolEliminar, Long rolActualizar,
			Long rolInsertar) {
		this.id = id;
		this.msegRoles = msegRoles;
		this.msegModulos = msegModulos;
		this.rolConsulta = rolConsulta;
		this.rolEliminar = rolEliminar;
		this.rolActualizar = rolActualizar;
		this.rolInsertar = rolInsertar;
 
	}
	
	public MsegRolmodulos( MsegRoles msegRoles,
			MsegModulos msegModulos, Long rolConsulta,
			Long rolEliminar, Long rolActualizar,
			Long rolInsertar) {
		
		MsegRolmodulosId id = new MsegRolmodulosId(); 
		id.setModCodigo(msegModulos.getModCodigo());
		id.setRolCodigo(msegRoles.getRolCodigo());
		this.id = id;
	 
	}

	/**
	 * @return
	 * @uml.property  name="id"
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "modCodigo", column = @Column(name = "MOD_CODIGO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "rolCodigo", column = @Column(name = "ROL_CODIGO", nullable = false, precision = 22, scale = 0)) })
	public MsegRolmodulosId getId() {
		return this.id;
	}

	/**
	 * @param  id
	 * @uml.property  name="id"
	 */
	public void setId(MsegRolmodulosId id) {
		this.id = id;
	}

	/**
	 * @return
	 * @uml.property  name="msegRoles"
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_CODIGO", nullable = false, insertable = false, updatable = false)
	public MsegRoles getMsegRoles() {
		return this.msegRoles;
	}

	/**
	 * @param  msegRoles
	 * @uml.property  name="msegRoles"
	 */
	public void setMsegRoles(MsegRoles msegRoles) {
		this.msegRoles = msegRoles;
	}

	/**
	 * @return
	 * @uml.property  name="msegModulos"
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOD_CODIGO", nullable = false, insertable = false, updatable = false)
	public MsegModulos getMsegModulos() {
		return this.msegModulos;
	}

	/**
	 * @param  msegModulos
	 * @uml.property  name="msegModulos"
	 */
	public void setMsegModulos(MsegModulos msegModulos) {
		this.msegModulos = msegModulos;
		
	}

	/**
	 * @return
	 * @uml.property  name="rolConsulta"
	 */
	@Column(name = "ROL_CONSULTA", precision = 22, scale = 0)
	public Long getRolConsulta() {
		return this.rolConsulta;
	}

	/**
	 * @param  rolConsulta
	 * @uml.property  name="rolConsulta"
	 */
	public void setRolConsulta(Long rolConsulta) {
		this.rolConsulta = rolConsulta;
	 }

	/**
	 * @return
	 * @uml.property  name="rolEliminar"
	 */
	@Column(name = "ROL_ELIMINAR", precision = 22, scale = 0)
	public Long getRolEliminar() {
		return this.rolEliminar;
	}

	/**
	 * @param  rolEliminar
	 * @uml.property  name="rolEliminar"
	 */
	public void setRolEliminar(Long rolEliminar) {
		this.rolEliminar = rolEliminar;
	 	}

	/**
	 * @return
	 * @uml.property  name="rolActualizar"
	 */
	@Column(name = "ROL_ACTUALIZAR", precision = 22, scale = 0)
	public Long getRolActualizar() {
		return this.rolActualizar;
	}

	/**
	 * @param  rolActualizar
	 * @uml.property  name="rolActualizar"
	 */
	public void setRolActualizar(Long rolActualizar) {
		this.rolActualizar = rolActualizar;
	 }

	/**
	 * @return
	 * @uml.property  name="rolInsertar"
	 */
	@Column(name = "ROL_INSERTAR", precision = 22, scale = 0)
	public Long getRolInsertar() {
		return this.rolInsertar;
	}

	/**
	 * @param  rolInsertar
	 * @uml.property  name="rolInsertar"
	 */
	public void setRolInsertar(Long rolInsertar) {
		this.rolInsertar = rolInsertar;
	 }
	
}
