package com.leasing.popular.wf.table.negocio.estudio;

//Generated 5/02/2010 08:55:46 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.leasing.popular.wf.table.negocio.negocio.McomNegocio;
import com.leasing.popular.wf.table.negocio.persona.McomPersonas;
import com.leasing.popular.wf.table.parametros.valores.MpaValores;

/**
 * McomEstudio generated by hbm2java
 */
@Entity
@Table(name = "MCOM_ESTUDIO")
public class McomEstudio implements java.io.Serializable {

	/**
	 * @uml.property name="estId"
	 */
	private BigDecimal estId;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresRecoriesgo"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresRecoriesgo;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega2"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresCaunega2;
	/**
	 * @uml.property name="mcomNegocio"
	 * @uml.associationEnd
	 */
	private McomNegocio mcomNegocio;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresAnalista1"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresAnalista1;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega1"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresCaunega1;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresNiveldeter"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresNiveldeter;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresAnalista2"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresAnalista2;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresCausaldevol"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresCausaldevol;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresDeterfinal"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresDeterfinal;
	/**
	 * @uml.property name="mcomPersonas"
	 * @uml.associationEnd
	 */
	private McomPersonas mcomPersonas;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresMarcaseg"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresMarcaseg;
	/**
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega3"
	 * @uml.associationEnd
	 */
	private MpaValores mpaValoresByFkEstudioValoresCaunega3;
	/**
	 * @uml.property name="estContRiesg"
	 */
	private String estContRiesg;
	/**
	 * @uml.property name="estDevueltoComercial1"
	 */
	private Date estDevueltoComercial1;
	/**
	 * @uml.property name="estDevueltoComercial2"
	 */
	private Date estDevueltoComercial2;
	/**
	 * @uml.property name="estDevueltoComercial3"
	 */
	private Date estDevueltoComercial3;
	/**
	 * @uml.property name="estFechaEstudio"
	 */
	private Date estFechaEstudio;
	/**
	 * @uml.property name="estNivelActivos"
	 */
	private BigDecimal estNivelActivos;
	/**
	 * @uml.property name="estCorteNivelActivos"
	 */
	private Date estCorteNivelActivos;
	/**
	 * @uml.property name="estTerminacion"
	 */
	private Date estTerminacion;
	/**
	 * @uml.property name="estFechaRiesgo"
	 */
	private Date estFechaRiesgo;
	/**
	 * @uml.property name="estDecisionComite"
	 */
	private Date estDecisionComite;
	/**
	 * @uml.property name="estRemisionBanco"
	 */
	private Date estRemisionBanco;
	/**
	 * @uml.property name="estRecepcionBanco"
	 */
	private Date estRecepcionBanco;
	/**
	 * @uml.property name="estFechaDeterminacion"
	 */
	private Date estFechaDeterminacion;
	/**
	 * @uml.property name="estMontoAprobado"
	 */
	private BigDecimal estMontoAprobado;
	/**
	 * @uml.property name="estVerificacionInformacion"
	 */
	private Date estVerificacionInformacion;
	/**
	 * @uml.property name="estObservaciones"
	 */
	private String estObservaciones;
	/**
	 * @uml.property name="estFechaReproceso"
	 */
	private Date estFechaReproceso;

	private Long estDisabled;

	public McomEstudio() {
	}

	public McomEstudio(McomNegocio mcomNegocio) {
		this.mcomNegocio = mcomNegocio;
	}

	public McomEstudio(MpaValores mpaValoresByFkEstudioValoresRecoriesgo,
			MpaValores mpaValoresByFkEstudioValoresCaunega2,
			McomNegocio mcomNegocio,
			MpaValores mpaValoresByFkEstudioValoresAnalista1,
			MpaValores mpaValoresByFkEstudioValoresCaunega1,
			MpaValores mpaValoresByFkEstudioValoresNiveldeter,
			MpaValores mpaValoresByFkEstudioValoresAnalista2,
			MpaValores mpaValoresByFkEstudioValoresCausaldevol,
			MpaValores mpaValoresByFkEstudioValoresDeterfinal,
			McomPersonas mcomPersonas,
			MpaValores mpaValoresByFkEstudioValoresMarcaseg,
			MpaValores mpaValoresByFkEstudioValoresCaunega3,
			String estContRiesg, Date estDevueltoComercial1,
			Date estDevueltoComercial2, Date estDevueltoComercial3,
			Date estFechaEstudio, BigDecimal estNivelActivos,
			Date estCorteNivelActivos, Date estTerminacion,
			Date estFechaRiesgo, Date estDecisionComite, Date estRemisionBanco,
			Date estRecepcionBanco, Date estFechaDeterminacion,
			BigDecimal estMontoAprobado, Date estVerificacionInformacion,
			String estObservaciones, Date estFechaReproceso) {
		this.mpaValoresByFkEstudioValoresRecoriesgo = mpaValoresByFkEstudioValoresRecoriesgo;
		this.mpaValoresByFkEstudioValoresCaunega2 = mpaValoresByFkEstudioValoresCaunega2;
		this.mcomNegocio = mcomNegocio;
		this.mpaValoresByFkEstudioValoresAnalista1 = mpaValoresByFkEstudioValoresAnalista1;
		this.mpaValoresByFkEstudioValoresCaunega1 = mpaValoresByFkEstudioValoresCaunega1;
		this.mpaValoresByFkEstudioValoresNiveldeter = mpaValoresByFkEstudioValoresNiveldeter;
		this.mpaValoresByFkEstudioValoresAnalista2 = mpaValoresByFkEstudioValoresAnalista2;
		this.mpaValoresByFkEstudioValoresCausaldevol = mpaValoresByFkEstudioValoresCausaldevol;
		this.mpaValoresByFkEstudioValoresDeterfinal = mpaValoresByFkEstudioValoresDeterfinal;
		this.mcomPersonas = mcomPersonas;
		this.mpaValoresByFkEstudioValoresMarcaseg = mpaValoresByFkEstudioValoresMarcaseg;
		this.mpaValoresByFkEstudioValoresCaunega3 = mpaValoresByFkEstudioValoresCaunega3;
		this.estContRiesg = estContRiesg;
		this.estDevueltoComercial1 = estDevueltoComercial1;
		this.estDevueltoComercial2 = estDevueltoComercial2;
		this.estDevueltoComercial3 = estDevueltoComercial3;
		this.estFechaEstudio = estFechaEstudio;
		this.estNivelActivos = estNivelActivos;
		this.estCorteNivelActivos = estCorteNivelActivos;
		this.estTerminacion = estTerminacion;
		this.estFechaRiesgo = estFechaRiesgo;
		this.estDecisionComite = estDecisionComite;
		this.estRemisionBanco = estRemisionBanco;
		this.estRecepcionBanco = estRecepcionBanco;
		this.estFechaDeterminacion = estFechaDeterminacion;
		this.estMontoAprobado = estMontoAprobado;
		this.estVerificacionInformacion = estVerificacionInformacion;
		this.estObservaciones = estObservaciones;
		this.estFechaReproceso = estFechaReproceso;
	}

	@Id
	@Column(name = "EST_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstId() {
		return this.estId;
	}

	/**
	 * @param estId
	 * @uml.property name="estId"
	 */
	public void setEstId(BigDecimal estId) {
		this.estId = estId;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresRecoriesgo"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_RECOMENDACION_RIESGO", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_PARA_RECRIESGO", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresRecoriesgo() {
		return this.mpaValoresByFkEstudioValoresRecoriesgo;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresRecoriesgo
	 * @uml.property name="mpaValoresByFkEstudioValoresRecoriesgo"
	 */
	public void setMpaValoresByFkEstudioValoresRecoriesgo(
			MpaValores mpaValoresByFkEstudioValoresRecoriesgo) {
		this.mpaValoresByFkEstudioValoresRecoriesgo = mpaValoresByFkEstudioValoresRecoriesgo;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega2"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_CAUSAL_NEGACION2", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_PARA_CAUSALNEG2", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresCaunega2() {
		return this.mpaValoresByFkEstudioValoresCaunega2;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresCaunega2
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega2"
	 */
	public void setMpaValoresByFkEstudioValoresCaunega2(
			MpaValores mpaValoresByFkEstudioValoresCaunega2) {
		this.mpaValoresByFkEstudioValoresCaunega2 = mpaValoresByFkEstudioValoresCaunega2;
	}

	/**
	 * @return
	 * @uml.property name="mcomNegocio"
	 */
	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public McomNegocio getMcomNegocio() {
		return this.mcomNegocio;
	}

	/**
	 * @param mcomNegocio
	 * @uml.property name="mcomNegocio"
	 */
	public void setMcomNegocio(McomNegocio mcomNegocio) {
		this.mcomNegocio = mcomNegocio;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresAnalista1"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_ANALISTA1", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_PARA_ANALISTA1", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresAnalista1() {
		return this.mpaValoresByFkEstudioValoresAnalista1;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresAnalista1
	 * @uml.property name="mpaValoresByFkEstudioValoresAnalista1"
	 */
	public void setMpaValoresByFkEstudioValoresAnalista1(
			MpaValores mpaValoresByFkEstudioValoresAnalista1) {
		this.mpaValoresByFkEstudioValoresAnalista1 = mpaValoresByFkEstudioValoresAnalista1;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega1"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_CAUSAL_NEGACION1", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_PARA_CAUSALNEG1", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresCaunega1() {
		return this.mpaValoresByFkEstudioValoresCaunega1;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresCaunega1
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega1"
	 */
	public void setMpaValoresByFkEstudioValoresCaunega1(
			MpaValores mpaValoresByFkEstudioValoresCaunega1) {
		this.mpaValoresByFkEstudioValoresCaunega1 = mpaValoresByFkEstudioValoresCaunega1;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresNiveldeter"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_PARA_NIVELDETER", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_NIVEL_DETERMINACION", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresNiveldeter() {
		return this.mpaValoresByFkEstudioValoresNiveldeter;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresNiveldeter
	 * @uml.property name="mpaValoresByFkEstudioValoresNiveldeter"
	 */
	public void setMpaValoresByFkEstudioValoresNiveldeter(
			MpaValores mpaValoresByFkEstudioValoresNiveldeter) {
		this.mpaValoresByFkEstudioValoresNiveldeter = mpaValoresByFkEstudioValoresNiveldeter;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresAnalista2"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_ANALISTA2", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_PARA_ANALISTA2", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresAnalista2() {
		return this.mpaValoresByFkEstudioValoresAnalista2;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresAnalista2
	 * @uml.property name="mpaValoresByFkEstudioValoresAnalista2"
	 */
	public void setMpaValoresByFkEstudioValoresAnalista2(
			MpaValores mpaValoresByFkEstudioValoresAnalista2) {
		this.mpaValoresByFkEstudioValoresAnalista2 = mpaValoresByFkEstudioValoresAnalista2;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresCausaldevol"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_PARA_CAUSALDEVOL", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_CAUSAL_DEVOLUCION", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresCausaldevol() {
		return this.mpaValoresByFkEstudioValoresCausaldevol;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresCausaldevol
	 * @uml.property name="mpaValoresByFkEstudioValoresCausaldevol"
	 */
	public void setMpaValoresByFkEstudioValoresCausaldevol(
			MpaValores mpaValoresByFkEstudioValoresCausaldevol) {
		this.mpaValoresByFkEstudioValoresCausaldevol = mpaValoresByFkEstudioValoresCausaldevol;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresDeterfinal"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_DETERMINACION_FINAL", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_PARA_DETERFINAL", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresDeterfinal() {
		return this.mpaValoresByFkEstudioValoresDeterfinal;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresDeterfinal
	 * @uml.property name="mpaValoresByFkEstudioValoresDeterfinal"
	 */
	public void setMpaValoresByFkEstudioValoresDeterfinal(
			MpaValores mpaValoresByFkEstudioValoresDeterfinal) {
		this.mpaValoresByFkEstudioValoresDeterfinal = mpaValoresByFkEstudioValoresDeterfinal;
	}

	/**
	 * @return
	 * @uml.property name="mcomPersonas"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_ID_CLIENTE", referencedColumnName = "PER_IDENTIFICACION"),
			@JoinColumn(name = "EST_TIPO_ID_CLIENTE", referencedColumnName = "PER_TIPO_IDENTIFICACION"),
			@JoinColumn(name = "EST_PARA_TIPO_ID_CLIENTE", referencedColumnName = "PER_PARA_TIPO_ID") })
	public McomPersonas getMcomPersonas() {
		return this.mcomPersonas;
	}

	/**
	 * @param mcomPersonas
	 * @uml.property name="mcomPersonas"
	 */
	public void setMcomPersonas(McomPersonas mcomPersonas) {
		this.mcomPersonas = mcomPersonas;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresMarcaseg"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_PARA_MARCASEG", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_MARCA_SEGUIMIENTO", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresMarcaseg() {
		return this.mpaValoresByFkEstudioValoresMarcaseg;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresMarcaseg
	 * @uml.property name="mpaValoresByFkEstudioValoresMarcaseg"
	 */
	public void setMpaValoresByFkEstudioValoresMarcaseg(
			MpaValores mpaValoresByFkEstudioValoresMarcaseg) {
		this.mpaValoresByFkEstudioValoresMarcaseg = mpaValoresByFkEstudioValoresMarcaseg;
	}

	/**
	 * @return
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega3"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "EST_CAUSAL_NEGACION3", referencedColumnName = "VAR_CODIGO"),
			@JoinColumn(name = "EST_PARA_CAUSALNEG3", referencedColumnName = "PAR_CODIGO") })
	public MpaValores getMpaValoresByFkEstudioValoresCaunega3() {
		return this.mpaValoresByFkEstudioValoresCaunega3;
	}

	/**
	 * @param mpaValoresByFkEstudioValoresCaunega3
	 * @uml.property name="mpaValoresByFkEstudioValoresCaunega3"
	 */
	public void setMpaValoresByFkEstudioValoresCaunega3(
			MpaValores mpaValoresByFkEstudioValoresCaunega3) {
		this.mpaValoresByFkEstudioValoresCaunega3 = mpaValoresByFkEstudioValoresCaunega3;
	}

	/**
	 * @return
	 * @uml.property name="estContRiesg"
	 */
	@Column(name = "EST_CONT_RIESG", length = 10)
	public String getEstContRiesg() {
		return this.estContRiesg;
	}

	/**
	 * @param estContRiesg
	 * @uml.property name="estContRiesg"
	 */
	public void setEstContRiesg(String estContRiesg) {
		this.estContRiesg = estContRiesg;
	}

	/**
	 * @return
	 * @uml.property name="estDevueltoComercial1"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_DEVUELTO_COMERCIAL1", length = 7)
	public Date getEstDevueltoComercial1() {
		return this.estDevueltoComercial1;
	}

	/**
	 * @param estDevueltoComercial1
	 * @uml.property name="estDevueltoComercial1"
	 */
	public void setEstDevueltoComercial1(Date estDevueltoComercial1) {
		this.estDevueltoComercial1 = estDevueltoComercial1;
	}

	/**
	 * @return
	 * @uml.property name="estDevueltoComercial2"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_DEVUELTO_COMERCIAL2", length = 7)
	public Date getEstDevueltoComercial2() {
		return this.estDevueltoComercial2;
	}

	/**
	 * @param estDevueltoComercial2
	 * @uml.property name="estDevueltoComercial2"
	 */
	public void setEstDevueltoComercial2(Date estDevueltoComercial2) {
		this.estDevueltoComercial2 = estDevueltoComercial2;
	}

	/**
	 * @return
	 * @uml.property name="estDevueltoComercial3"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_DEVUELTO_COMERCIAL3", length = 7)
	public Date getEstDevueltoComercial3() {
		return this.estDevueltoComercial3;
	}

	/**
	 * @param estDevueltoComercial3
	 * @uml.property name="estDevueltoComercial3"
	 */
	public void setEstDevueltoComercial3(Date estDevueltoComercial3) {
		this.estDevueltoComercial3 = estDevueltoComercial3;
	}

	/**
	 * @return
	 * @uml.property name="estFechaEstudio"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_FECHA_ESTUDIO", length = 7)
	public Date getEstFechaEstudio() {
		return this.estFechaEstudio;
	}

	/**
	 * @param estFechaEstudio
	 * @uml.property name="estFechaEstudio"
	 */
	public void setEstFechaEstudio(Date estFechaEstudio) {
		this.estFechaEstudio = estFechaEstudio;
	}

	/**
	 * @return
	 * @uml.property name="estNivelActivos"
	 */
	@Column(name = "EST_NIVEL_ACTIVOS", precision = 126, scale = 0)
	public BigDecimal getEstNivelActivos() {
		return this.estNivelActivos;
	}

	/**
	 * @param estNivelActivos
	 * @uml.property name="estNivelActivos"
	 */
	public void setEstNivelActivos(BigDecimal estNivelActivos) {
		this.estNivelActivos = estNivelActivos;
	}

	/**
	 * @return
	 * @uml.property name="estCorteNivelActivos"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_CORTE_NIVEL_ACTIVOS", length = 7)
	public Date getEstCorteNivelActivos() {
		return this.estCorteNivelActivos;
	}

	/**
	 * @param estCorteNivelActivos
	 * @uml.property name="estCorteNivelActivos"
	 */
	public void setEstCorteNivelActivos(Date estCorteNivelActivos) {
		this.estCorteNivelActivos = estCorteNivelActivos;
	}

	/**
	 * @return
	 * @uml.property name="estTerminacion"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_TERMINACION", length = 7)
	public Date getEstTerminacion() {
		return this.estTerminacion;
	}

	/**
	 * @param estTerminacion
	 * @uml.property name="estTerminacion"
	 */
	public void setEstTerminacion(Date estTerminacion) {
		this.estTerminacion = estTerminacion;
	}

	/**
	 * @return
	 * @uml.property name="estFechaRiesgo"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_FECHA_RIESGO", length = 7)
	public Date getEstFechaRiesgo() {
		return this.estFechaRiesgo;
	}

	/**
	 * @param estFechaRiesgo
	 * @uml.property name="estFechaRiesgo"
	 */
	public void setEstFechaRiesgo(Date estFechaRiesgo) {
		this.estFechaRiesgo = estFechaRiesgo;
	}

	/**
	 * @return
	 * @uml.property name="estDecisionComite"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_DECISION_COMITE", length = 7)
	public Date getEstDecisionComite() {
		return this.estDecisionComite;
	}

	/**
	 * @param estDecisionComite
	 * @uml.property name="estDecisionComite"
	 */
	public void setEstDecisionComite(Date estDecisionComite) {
		this.estDecisionComite = estDecisionComite;
	}

	/**
	 * @return
	 * @uml.property name="estRemisionBanco"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_REMISION_BANCO", length = 7)
	public Date getEstRemisionBanco() {
		return this.estRemisionBanco;
	}

	/**
	 * @param estRemisionBanco
	 * @uml.property name="estRemisionBanco"
	 */
	public void setEstRemisionBanco(Date estRemisionBanco) {
		this.estRemisionBanco = estRemisionBanco;
	}

	/**
	 * @return
	 * @uml.property name="estRecepcionBanco"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_RECEPCION_BANCO", length = 7)
	public Date getEstRecepcionBanco() {
		return this.estRecepcionBanco;
	}

	/**
	 * @param estRecepcionBanco
	 * @uml.property name="estRecepcionBanco"
	 */
	public void setEstRecepcionBanco(Date estRecepcionBanco) {
		this.estRecepcionBanco = estRecepcionBanco;
	}

	/**
	 * @return
	 * @uml.property name="estFechaDeterminacion"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_FECHA_DETERMINACION", length = 7)
	public Date getEstFechaDeterminacion() {
		return this.estFechaDeterminacion;
	}

	/**
	 * @param estFechaDeterminacion
	 * @uml.property name="estFechaDeterminacion"
	 */
	public void setEstFechaDeterminacion(Date estFechaDeterminacion) {
		this.estFechaDeterminacion = estFechaDeterminacion;
	}

	/**
	 * @return
	 * @uml.property name="estMontoAprobado"
	 */
	@Column(name = "EST_MONTO_APROBADO", precision = 126, scale = 0)
	public BigDecimal getEstMontoAprobado() {
		return this.estMontoAprobado;
	}

	/**
	 * @param estMontoAprobado
	 * @uml.property name="estMontoAprobado"
	 */
	public void setEstMontoAprobado(BigDecimal estMontoAprobado) {
		this.estMontoAprobado = estMontoAprobado;
	}

	/**
	 * @return
	 * @uml.property name="estVerificacionInformacion"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_VERIFICACION_INFORMACION", length = 7)
	public Date getEstVerificacionInformacion() {
		return this.estVerificacionInformacion;
	}

	/**
	 * @param estVerificacionInformacion
	 * @uml.property name="estVerificacionInformacion"
	 */
	public void setEstVerificacionInformacion(Date estVerificacionInformacion) {
		this.estVerificacionInformacion = estVerificacionInformacion;
	}

	/**
	 * @return
	 * @uml.property name="estObservaciones"
	 */
	@Column(name = "EST_OBSERVACIONES", length = 50)
	public String getEstObservaciones() {
		return this.estObservaciones;
	}

	/**
	 * @param estObservaciones
	 * @uml.property name="estObservaciones"
	 */
	public void setEstObservaciones(String estObservaciones) {
		this.estObservaciones = estObservaciones;
	}

	/**
	 * @return
	 * @uml.property name="estFechaReproceso"
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EST_FECHA_REPROCESO", length = 7)
	public Date getEstFechaReproceso() {
		return this.estFechaReproceso;
	}

	/**
	 * @param estFechaReproceso
	 * @uml.property name="estFechaReproceso"
	 */
	public void setEstFechaReproceso(Date estFechaReproceso) {
		this.estFechaReproceso = estFechaReproceso;
	}

	@Column(name = "EST_DISABLED", length = 1)
	public Long getEstDisabled() {
		return estDisabled;
	}

	public void setEstDisabled(Long estDisabled) {
		this.estDisabled = estDisabled;
	}
}
