package com.leasing.popular.wf.table.operaciones.observaciones;// default package
// Generated 19/03/2010 10:09:21 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MoperObservacionesId generated by hbm2java
 */
@Embeddable
public class MoperObservacionesId implements java.io.Serializable {

	private Long operId;
	private Long staId;

	public MoperObservacionesId() {
	}

	public MoperObservacionesId(Long operId, Long staId) {
		this.operId = operId;
		this.staId = staId;
	}

	@Column(name = "OPER_ID", nullable = false, precision = 22, scale = 0)
	public Long getOperId() {
		return this.operId;
	}

	public void setOperId(Long operId) {
		this.operId = operId;
	}

	@Column(name = "STA_ID", nullable = false, precision = 22, scale = 0)
	public Long getStaId() {
		return this.staId;
	}

	public void setStaId(Long staId) {
		this.staId = staId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MoperObservacionesId))
			return false;
		MoperObservacionesId castOther = (MoperObservacionesId) other;

		return ((this.getOperId() == castOther.getOperId()) || (this
				.getOperId() != null
				&& castOther.getOperId() != null && this.getOperId().equals(
				castOther.getOperId())))
				&& ((this.getStaId() == castOther.getStaId()) || (this
						.getStaId() != null
						&& castOther.getStaId() != null && this.getStaId()
						.equals(castOther.getStaId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOperId() == null ? 0 : this.getOperId().hashCode());
		result = 37 * result
				+ (getStaId() == null ? 0 : this.getStaId().hashCode());
		return result;
	}

}
