package com.leasing.popular.wf.table.operaciones.observaciones;
// default package
// Generated 19/03/2010 10:09:21 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.leasing.popular.wf.table.operaciones.operaciones.MoperOperaciones;
import com.leasing.popular.wf.table.parametros.status.MoperStatus;


/**
 * MoperObservaciones generated by hbm2java
 */
@Entity
@Table(name = "MOPER_OBSERVACIONES")
public class MoperObservaciones implements java.io.Serializable {

	private MoperObservacionesId id;
	private MoperStatus moperStatus;
	private MoperOperaciones moperOperaciones;
	private String obsObservaciones;
	private Date operFecha;

	public MoperObservaciones() {
	}

	public MoperObservaciones(MoperObservacionesId id, MoperStatus moperStatus,
			MoperOperaciones moperOperaciones) {
		this.id = id;
		this.moperStatus = moperStatus;
		this.moperOperaciones = moperOperaciones;
	}

	public MoperObservaciones(MoperObservacionesId id, MoperStatus moperStatus,
			MoperOperaciones moperOperaciones, String obsObservaciones1,
			String obsObservaciones2, String obsObservaciones3,
			String obsObservaciones4, Date operFecha) {
		this.id = id;
		this.moperStatus = moperStatus;
		this.moperOperaciones = moperOperaciones;
		this.obsObservaciones= obsObservaciones1;
		this.operFecha = operFecha;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "operId", column = @Column(name = "OPER_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "staId", column = @Column(name = "STA_ID", nullable = false, precision = 22, scale = 0)) })
	public MoperObservacionesId getId() {
		return this.id;
	}

	public void setId(MoperObservacionesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STA_ID", nullable = false, insertable = false, updatable = false)
	public MoperStatus getMoperStatus() {
		return this.moperStatus;
	}

	public void setMoperStatus(MoperStatus moperStatus) {
		this.moperStatus = moperStatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OPER_ID", nullable = false, insertable = false, updatable = false)
	public MoperOperaciones getMoperOperaciones() {
		return this.moperOperaciones;
	}

	public void setMoperOperaciones(MoperOperaciones moperOperaciones) {
		this.moperOperaciones = moperOperaciones;
	}

	@Column(name = "OBS_OBSERVACIONES", length = 4000)
	public String getObsObservaciones() {
		return this.obsObservaciones;
	}

	public void setObsObservaciones(String obsObservaciones1) {
		this.obsObservaciones = obsObservaciones1;
	}
 
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPER_FECHA", length = 7)
	public Date getOperFecha() {
		return this.operFecha;
	}

	public void setOperFecha(Date operFecha) {
		this.operFecha = operFecha;
	}

}
