package com.leasing.popular.wf.table.seguridad.estado;

// Generated 24/09/2009 08:39:52 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jboss.seam.annotations.Name;

/**
 * MsegEstados generated by hbm2java
 */
@Entity
@Name("msegEstados")
@Table(name = "MSEG_ESTADOS")
public class MsegEstados implements java.io.Serializable {

	/**
	 * @uml.property  name="estCodigo"
	 */
	private Long estCodigo;
	/**
	 * @uml.property  name="estNombre"
	 */
	private String estNombre;
	 
	public MsegEstados() {
	}

	public MsegEstados(long estCodigo) {
		this.estCodigo = estCodigo;
	}

	public MsegEstados(long estCodigo, String estNombre ) {
		this.estCodigo = estCodigo;
		this.estNombre = estNombre; 
	}

	/**
	 * @return
	 * @uml.property  name="estCodigo"
	 */
	@Id
	@Column(name = "EST_CODIGO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getEstCodigo() {
		return this.estCodigo;
	}

	/**
	 * @param  estCodigo
	 * @uml.property  name="estCodigo"
	 */
	public void setEstCodigo(Long estCodigo) {
		this.estCodigo = estCodigo;
	}

	/**
	 * @return
	 * @uml.property  name="estNombre"
	 */
	@Column(name = "EST_NOMBRE", length = 15)
	public String getEstNombre() {
		return this.estNombre.toUpperCase();
	}

	/**
	 * @param  estNombre
	 * @uml.property  name="estNombre"
	 */
	public void setEstNombre(String estNombre) {
		this.estNombre = estNombre;
	}

 

}
