package com.leasing.popular.wf.table.parametros.status;
// default package
// Generated 19/03/2010 10:09:21 AM by Hibernate Tools 3.2.4.GA

 
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MoperStatus generated by hbm2java
 */
@Entity
@Table(name = "MOPER_STATUS")
public class MoperStatus implements java.io.Serializable {

	private Long staId;
	private String staNombre;

	public MoperStatus() {
	}

	public MoperStatus(Long staId) {
		this.staId = staId;
	}

	public MoperStatus(Long staId, String staNombre,
			Set moperObservacioneses) {
		this.staId = staId;
		this.staNombre = staNombre;

	}

	@Id
	@Column(name = "STA_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getStaId() {
		return this.staId;
	}

	public void setStaId(Long staId) {
		this.staId = staId;
	}

	@Column(name = "STA_NOMBRE", length = 1)
	public String getStaNombre() {
		return this.staNombre;
	}

	public void setStaNombre(String staNombre) {
		this.staNombre = staNombre;
	}

 

}
