package com.leasing.popular.wf.table.parametros.valores;

// Generated 12/12/2009 10:26:43 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.leasing.popular.wf.table.parametros.parametro.MpaParametro;

/**
 * MpaValores generated by hbm2java
 */
@Entity
@Table(name = "MPA_VALORES")
public class MpaValores implements java.io.Serializable {

	private MpaValoresId id;
	private MpaParametro mpaParametro;
	private String varNombre; 


	public MpaValores() {
	}

	public MpaValores(MpaValoresId id, MpaParametro mpaParametro) {
		this.id = id;
		this.mpaParametro = mpaParametro;
	}

	public MpaValores(MpaValoresId id, MpaParametro mpaParametro,
			String varNombre ) {
		this.id = id;
		this.mpaParametro = mpaParametro;
		this.varNombre = varNombre; 
	}

	/**
	 * @return
	 * @uml.property  name="id"
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "varCodigo", column = @Column(name = "VAR_CODIGO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "parCodigo", column = @Column(name = "PAR_CODIGO", nullable = false, precision = 22, scale = 0)) })
	public MpaValoresId getId() {
		return this.id;
	}

	/**
	 * @param  id
	 * @uml.property  name="id"
	 */
	public void setId(MpaValoresId id) {
		this.id = id;
	}

	/**
	 * @return
	 * @uml.property  name="mpaParametro"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PAR_CODIGO", nullable = false, insertable = false, updatable = false)
	public MpaParametro getMpaParametro() {
		return this.mpaParametro;
	}

	/**
	 * @param  mpaParametro
	 * @uml.property  name="mpaParametro"
	 */
	public void setMpaParametro(MpaParametro mpaParametro) {
		this.mpaParametro = mpaParametro;
	}

	/**
	 * @return
	 * @uml.property  name="varNombre"
	 */
	@Column(name = "VAR_NOMBRE")
	public String getVarNombre() {
		return this.varNombre;
	}

	/**
	 * @param  varNombre
	 * @uml.property  name="varNombre"
	 */
	public void setVarNombre(String varNombre) {
		this.varNombre = varNombre.toUpperCase();
	}
 


}
