package com.leasing.popular.wf.table.negocio.persona;

//Generated 31/01/2010 08:01:20 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * McomPersonasId generated by hbm2java
 */
@Embeddable
public class McomPersonasId implements java.io.Serializable {

	/**
	 * @uml.property  name="perIdentificacion"
	 */
	private String perIdentificacion;
	/**
	 * @uml.property  name="perTipoIdentificacion"
	 */
	private Long perTipoIdentificacion;
	/**
	 * @uml.property  name="perParaTipoId"
	 */
	private Long perParaTipoId;

	public McomPersonasId() {
	}

	public McomPersonasId(String perIdentificacion,
			Long perTipoIdentificacion, Long perParaTipoId) {
		this.perIdentificacion = perIdentificacion;
		this.perTipoIdentificacion = perTipoIdentificacion;
		this.perParaTipoId = perParaTipoId;
	}

	/**
	 * @return
	 * @uml.property  name="perIdentificacion"
	 */
	@Column(name = "PER_IDENTIFICACION", nullable = false, length = 15)
	public String getPerIdentificacion() {
		return this.perIdentificacion;
	}

	/**
	 * @param  perIdentificacion
	 * @uml.property  name="perIdentificacion"
	 */
	public void setPerIdentificacion(String perIdentificacion) {
		this.perIdentificacion = perIdentificacion;
	}

	/**
	 * @return
	 * @uml.property  name="perTipoIdentificacion"
	 */
	@Column(name = "PER_TIPO_IDENTIFICACION", nullable = false, precision = 22, scale = 0)
	public Long getPerTipoIdentificacion() {
		return this.perTipoIdentificacion;
	}

	/**
	 * @param  perTipoIdentificacion
	 * @uml.property  name="perTipoIdentificacion"
	 */
	public void setPerTipoIdentificacion(Long perTipoIdentificacion) {
		this.perTipoIdentificacion = perTipoIdentificacion;
	}

	/**
	 * @return
	 * @uml.property  name="perParaTipoId"
	 */
	@Column(name = "PER_PARA_TIPO_ID", nullable = false, precision = 22, scale = 0)
	public Long getPerParaTipoId() {
		return this.perParaTipoId;
	}

	/**
	 * @param  perParaTipoId
	 * @uml.property  name="perParaTipoId"
	 */
	public void setPerParaTipoId(Long perParaTipoId) {
		this.perParaTipoId = perParaTipoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof McomPersonasId))
			return false;
		McomPersonasId castOther = (McomPersonasId) other;

		return ((this.getPerIdentificacion() == castOther
				.getPerIdentificacion()) || (this.getPerIdentificacion() != null
				&& castOther.getPerIdentificacion() != null && this
				.getPerIdentificacion()
				.equals(castOther.getPerIdentificacion())))
				&& ((this.getPerTipoIdentificacion() == castOther
						.getPerTipoIdentificacion()) || (this
						.getPerTipoIdentificacion() != null
						&& castOther.getPerTipoIdentificacion() != null && this
						.getPerTipoIdentificacion().equals(
								castOther.getPerTipoIdentificacion())))
				&& ((this.getPerParaTipoId() == castOther.getPerParaTipoId()) || (this
						.getPerParaTipoId() != null
						&& castOther.getPerParaTipoId() != null && this
						.getPerParaTipoId()
						.equals(castOther.getPerParaTipoId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPerIdentificacion() == null ? 0 : this
						.getPerIdentificacion().hashCode());
		result = 37
				* result
				+ (getPerTipoIdentificacion() == null ? 0 : this
						.getPerTipoIdentificacion().hashCode());
		result = 37
				* result
				+ (getPerParaTipoId() == null ? 0 : this.getPerParaTipoId()
						.hashCode());
		return result;
	}

}
