package com.leasing.popular.wf.table.seguridad.usuarios;

// Generated 25/11/2009 08:30:35 AM by Hibernate Tools 3.2.5.Beta


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MsegRolusuariosId generated by hbm2java
 */
@Embeddable
public class MsegRolusuariosId implements java.io.Serializable {

	/**
	 * @uml.property  name="roluRolCodigo"
	 */
	private Long roluRolCodigo;
	/**
	 * @uml.property  name="roluUsuCedula"
	 */
	private Long roluUsuCedula;

	public MsegRolusuariosId() {
	}

	public MsegRolusuariosId(Long roluRolCodigo, Long roluUsuCedula) {
		this.roluRolCodigo = roluRolCodigo;
		this.roluUsuCedula = roluUsuCedula;
	}

	/**
	 * @return
	 * @uml.property  name="roluRolCodigo"
	 */
	@Column(name = "ROLU_ROL_CODIGO", nullable = false, precision = 22, scale = 0)
	public Long getRoluRolCodigo() {
		return this.roluRolCodigo;
	}

	/**
	 * @param  roluRolCodigo
	 * @uml.property  name="roluRolCodigo"
	 */
	public void setRoluRolCodigo(Long roluRolCodigo) {
		this.roluRolCodigo = roluRolCodigo;
	}

	/**
	 * @return
	 * @uml.property  name="roluUsuCedula"
	 */
	@Column(name = "ROLU_USU_CEDULA", nullable = false, precision = 22, scale = 0)
	public Long getRoluUsuCedula() {
		return this.roluUsuCedula;
	}

	/**
	 * @param  roluUsuCedula
	 * @uml.property  name="roluUsuCedula"
	 */
	public void setRoluUsuCedula(Long roluUsuCedula) {
		this.roluUsuCedula = roluUsuCedula;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MsegRolusuariosId))
			return false;
		MsegRolusuariosId castOther = (MsegRolusuariosId) other;

		return ((this.getRoluRolCodigo() == castOther.getRoluRolCodigo()) || (this
				.getRoluRolCodigo() != null
				&& castOther.getRoluRolCodigo() != null && this
				.getRoluRolCodigo().equals(castOther.getRoluRolCodigo())))
				&& ((this.getRoluUsuCedula() == castOther.getRoluUsuCedula()) || (this
						.getRoluUsuCedula() != null
						&& castOther.getRoluUsuCedula() != null && this
						.getRoluUsuCedula()
						.equals(castOther.getRoluUsuCedula())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getRoluRolCodigo() == null ? 0 : this.getRoluRolCodigo()
						.hashCode());
		result = 37
				* result
				+ (getRoluUsuCedula() == null ? 0 : this.getRoluUsuCedula()
						.hashCode());
		return result;
	}

}
