package com.leasing.popular.wf.table.seguridad.usuarios;

// Generated 25/11/2009 08:30:35 AM by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.jboss.seam.annotations.Name;

import com.leasing.popular.wf.table.seguridad.roles.MsegRoles;

/**
 * MsegRolusuarios generated by hbm2java
 */
@Entity
@Name("msegRolusuarios")
@Table(name = "MSEG_ROLUSUARIOS")
public class MsegRolusuarios implements java.io.Serializable {

	/**
	 * @uml.property  name="id"
	 * @uml.associationEnd  
	 */
	private MsegRolusuariosId id;
	/**
	 * @uml.property  name="msegRoles"
	 * @uml.associationEnd  
	 */
	private MsegRoles msegRoles;
	/**
	 * @uml.property  name="msegUsuarios"
	 * @uml.associationEnd  
	 */
	private MsegUsuarios msegUsuarios;

	public MsegRolusuarios() {
	}

	public MsegRolusuarios(MsegRolusuariosId id, MsegRoles msegRoles,MsegUsuarios msegUsuarios) {
		this.id = id;
		this.msegRoles = msegRoles;
		this.msegUsuarios = msegUsuarios;
	}

	/**
	 * @return
	 * @uml.property  name="id"
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "roluRolCodigo", column = @Column(name = "ROLU_ROL_CODIGO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "roluUsuCedula", column = @Column(name = "ROLU_USU_CEDULA", nullable = false, precision = 22, scale = 0)) })
	public MsegRolusuariosId getId() {
		return this.id;
	}

	/**
	 * @param  id
	 * @uml.property  name="id"
	 */
	public void setId(MsegRolusuariosId id) {
		this.id = id;
	}
	/**
	 * @return
	 * @uml.property  name="msegRoles"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ROLU_ROL_CODIGO", nullable = false, insertable = false, updatable = false)
	public MsegRoles getMsegRoles() {
		return msegRoles;
	}

	
	
	
	/**
	 * @param  msegRoles
	 * @uml.property  name="msegRoles"
	 */
	public void setMsegRoles(MsegRoles msegRoles) {
		this.msegRoles = msegRoles;
	}
	/**
	 * @return
	 * @uml.property  name="msegUsuarios"
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ROLU_USU_CEDULA", nullable = false, insertable = false, updatable = false)
	public MsegUsuarios getMsegUsuarios() {
		return msegUsuarios;
	}

	/**
	 * @param  msegUsuarios
	 * @uml.property  name="msegUsuarios"
	 */
	public void setMsegUsuarios(MsegUsuarios msegUsuarios) {
		this.msegUsuarios = msegUsuarios;
	}
   
	 
}
