package com.leasing.popular.wf.table.operaciones.operaciones;// default package
// Generated 19/03/2010 10:09:21 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.leasing.popular.wf.table.parametros.status.MoperStatus;
import com.leasing.popular.wf.table.parametros.valores.MpaValores;

/**
 * MoperOperaciones generated by hbm2java
 */
@Entity
@Table(name = "MOPER_OPERACIONES")
public class MoperOperaciones implements java.io.Serializable {

	private Long operId;
	private MoperStatus moperStatus;
	private MpaValores mpaValores;
	private Double operValorSolicitado;
	private Double operValorAprobado;
	private String operContRiesgo;
	private Date operFechaEntrega;
	private Long operSimco;    
       
	  
	public MoperOperaciones() {
	}
     
	public MoperOperaciones(Long operId) {
		this.operId = operId;
	}

	public MoperOperaciones(Long operId, MoperStatus moperStatus,
			MpaValores mpaValores, Double operValorSolicitado,
			Double operValorAprobado, String operContRiesgo,
			Date operFechaEntrega, Long operSimco) {
		this.operId = operId;
		this.moperStatus = moperStatus;
		this.mpaValores = mpaValores;
		this.operValorSolicitado = operValorSolicitado;
		this.operValorAprobado = operValorAprobado;
		this.operContRiesgo = operContRiesgo;
		this.operFechaEntrega = operFechaEntrega;
		this.operSimco = operSimco;
	}

	@Id
	@Column(name = "OPER_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getOperId() {
		return this.operId;
	}

	public void setOperId(Long operId) {
		this.operId = operId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OPER_STATUS")
	public MoperStatus getMoperStatus() {
		return this.moperStatus;
	}

	public void setMoperStatus(MoperStatus moperStatus) {
		this.moperStatus = moperStatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns( {
			@JoinColumn(name = "OPER_PARA_ANALISTA", referencedColumnName = "PAR_CODIGO"),
			@JoinColumn(name = "OPER_ANALISTA", referencedColumnName = "VAR_CODIGO") })
	public MpaValores getMpaValores() {
		return this.mpaValores;
	}

	public void setMpaValores(MpaValores mpaValores) {
		this.mpaValores = mpaValores;
	}

	@Column(name = "OPER_VALOR_SOLICITADO", precision = 126, scale = 0)
	public Double getOperValorSolicitado() {
		return this.operValorSolicitado;
	}

	public void setOperValorSolicitado(Double operValorSolicitado) {
		this.operValorSolicitado = operValorSolicitado;
	}

	@Column(name = "OPER_VALOR_APROBADO", precision = 126, scale = 0)
	public Double getOperValorAprobado() {
		return this.operValorAprobado;
	}

	public void setOperValorAprobado(Double operValorAprobado) {
		this.operValorAprobado = operValorAprobado;
	}

	@Column(name = "OPER_CONT_RIESGO", length = 10)
	public String getOperContRiesgo() {
		return this.operContRiesgo;
	}

	public void setOperContRiesgo(String operContRiesgo) {
		this.operContRiesgo = operContRiesgo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPER_FECHA_ENTREGA", length = 7)
	public Date getOperFechaEntrega() {
		return this.operFechaEntrega;
	}

	public void setOperFechaEntrega(Date operFechaEntrega) {
		this.operFechaEntrega = operFechaEntrega;
	}

	@Column(name = "OPER_SIMCO", precision = 38, scale = 0)
	public Long getOperSimco() {
		return this.operSimco;
	}

	public void setOperSimco(Long operSimco) {
		this.operSimco = operSimco;
	}

}
