package com.leasing.popular.wf.table.seguridad.modulo;

 
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MsegRolmodulosId generated by hbm2java
 */
@Embeddable
public class MsegRolmodulosId implements java.io.Serializable {

	/**
	 * @uml.property  name="modCodigo"
	 */
	private Long modCodigo;
	/**
	 * @uml.property  name="rolCodigo"
	 */
	private Long rolCodigo;

	public MsegRolmodulosId() {
	}

	public MsegRolmodulosId(Long modCodigo, Long rolCodigo) {
		this.modCodigo = modCodigo;
		this.rolCodigo = rolCodigo;
	}

	/**
	 * @return
	 * @uml.property  name="modCodigo"
	 */
	@Column(name = "MOD_CODIGO", nullable = false, precision = 22, scale = 0)
	public Long getModCodigo() {
		return this.modCodigo;
	}

	/**
	 * @param  modCodigo
	 * @uml.property  name="modCodigo"
	 */
	public void setModCodigo(Long modCodigo) {
		this.modCodigo = modCodigo;
	}

	/**
	 * @return
	 * @uml.property  name="rolCodigo"
	 */
	@Column(name = "ROL_CODIGO", nullable = false, precision = 22, scale = 0)
	public Long getRolCodigo() {
		return this.rolCodigo;
	}

	/**
	 * @param  rolCodigo
	 * @uml.property  name="rolCodigo"
	 */
	public void setRolCodigo(Long rolCodigo) {
		this.rolCodigo = rolCodigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MsegRolmodulosId))
			return false;
		MsegRolmodulosId castOther = (MsegRolmodulosId) other;

		return ((this.getModCodigo() == castOther.getModCodigo()) || (this
				.getModCodigo() != null
				&& castOther.getModCodigo() != null && this.getModCodigo()
				.equals(castOther.getModCodigo())))
				&& ((this.getRolCodigo() == castOther.getRolCodigo()) || (this
						.getRolCodigo() != null
						&& castOther.getRolCodigo() != null && this
						.getRolCodigo().equals(castOther.getRolCodigo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getModCodigo() == null ? 0 : this.getModCodigo().hashCode());
		result = 37 * result
				+ (getRolCodigo() == null ? 0 : this.getRolCodigo().hashCode());
		return result;
	}

}
