package com.leasing.popular.wf.table.seguridad.modulo;
// Generated 24/10/2009 12:22:17 PM by Hibernate Tools 3.2.4.GA

 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Out;


/**
 * MsegModulos generated by hbm2java
 */
@Entity
@Name("msegModulos")
@Table(name = "MSEG_MODULOS")
public class MsegModulos implements java.io.Serializable {

	//@In(required=false) @Out
	/**
	 * @uml.property  name="msegMenu"
	 * @uml.associationEnd  
	 */
	private MsegMenu msegMenu;
	/**
	 * @uml.property  name="modCodigo"
	 */
	private long modCodigo;
	/**
	 * @uml.property  name="modNombre"
	 */
	private String modNombre;
	/**
	 * @uml.property  name="modUrl"
	 */
	private String modUrl;

	public MsegModulos() {
	}

	public MsegModulos(Long modCodigo,MsegMenu msegMenu) {
		this.modCodigo = modCodigo;
		this.msegMenu = msegMenu;
	}

	public MsegModulos(Long modCodigo, String modNombre,MsegMenu msegMenu) {
		this.modCodigo = modCodigo;
		this.modNombre = modNombre;
		this.msegMenu = msegMenu;
	}

	/**
	 * @return
	 * @uml.property  name="modCodigo"
	 */
	@Id
	@Column(name = "MOD_CODIGO", unique = true, nullable = false, precision = 22, scale = 0)
	public long getModCodigo() {
		return this.modCodigo;
	}

	/**
	 * @param  modCodigo
	 * @uml.property  name="modCodigo"
	 */
	public void setModCodigo(long modCodigo) {
		this.modCodigo = modCodigo;
	}

	/**
	 * @return
	 * @uml.property  name="modNombre"
	 */
	@Column(name = "MOD_NOMBRE", length = 15)
	public String getModNombre() {
		return this.modNombre;
	}

	/**
	 * @param  modNombre
	 * @uml.property  name="modNombre"
	 */
	public void setModNombre(String modNombre) {
		this.modNombre = modNombre;
	}
	
	
	
	/**
	 * @return
	 * @uml.property  name="modUrl"
	 */
	@Column(name = "MOD_URL", length = 150)
	public String getModUrl() {
		return modUrl;
	}

	/**
	 * @param  modUrl
	 * @uml.property  name="modUrl"
	 */
	public void setModUrl(String modUrl) {
		this.modUrl = modUrl;
	}

	/**
	 * @return
	 * @uml.property  name="msegMenu"
	 */
	@ManyToOne
	@JoinColumn(name="MEN_CODIGO")
	public MsegMenu getMsegMenu() {
		return msegMenu;
	}

	/**
	 * @param  msegMenu
	 * @uml.property  name="msegMenu"
	 */
	public void setMsegMenu(MsegMenu msegMenu) {
		this.msegMenu = msegMenu;
	}
}
